name: DingTalk Notify

on:
  push:
    branches:
      - develop
      - main
      - master
      - test

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Test DingTalk
        env:
          WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "msgtype":"text",
              "text":{
                "content":"GitHub 测试"
              }
            }'