name: DingTalk Notify

on:
  push:
    branches:
      - main
      - master
      - develop
      - test

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        run: |
          echo "Hello GitHub Actions"